homeassistant:
  auth_providers:
   - type: homeassistant
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables configuration UI
frontend: 
  javascript_version: latest
  themes: !include_dir_merge_named themes

config:

hassio:

#http:

updater:

conversation:

history: !include history.yaml

recorder: !include recorder.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-popup-card/popup-card.js
      type: js
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module

    - url: /local/hui-view-settings.js
      type: js
    - url: /local/popup-background.js
      type: js
      
    
    - url: 'https://fonts.googleapis.com/css?family=Raleway'
      type: css
    - url: 'https://fonts.googleapis.com/css?family=Oswald'
      type: css
    - url: 'https://fonts.googleapis.com/css?family=Quicksand'
      type: css

system_health:

#logbook:

sun:

ssdp:

zeroconf:

person:

mobile_app:

logger:
  default: critical

## HOME ASSISTANT CLOUD #################################################################
cloud:

## TTS ##################################################################################
tts:
  - platform: google_translate
    language: 'de'

## MEDIA PLAYER #########################################################################
media_player:
  - platform: androidtv
    name: FireTV - Wohnzimmer
    host: 192.168.0.78
    apps:
      com.amazon.tv.launcher: "Fire TV"
      com.netflix.ninja: "Netflix"
      com.amazon.avod: "Amazon Video"
      com.amazon.firetv.youtube: "YouTube"
    state_detection_rules:
      'com.amazon.tv.launcher':
        - 'standby'
      'com.netflix.ninja':
        - 'media_session_state'
      'com.amazon.avod':
        - 'media_session_state'
  
## HUE ##################################################################################
hue:
  bridges:
    - host: 192.168.0.22
      allow_hue_groups: true
      allow_unreachable: true

## DEVICE TRACKERS ######################################################################
device_tracker:
  - platform: fritz
    host: 192.168.0.1
    track_new_devices: True
    consider_home: 90
  - platform: bluetooth_tracker
  - platform: google_maps
    username: !secret gmaps_tracker_mail
    max_gps_accuracy: 200
  - platform: mqtt_json
    devices:
      niu: home/niu/position

life360:
  max_update_wait:
    minutes: 30
  warning_threshold: 10
  error_threshold: 15

## TELEGRAM #############################################################################
notify:
  - name: telegram_bot
    platform: telegram
    chat_id: !secret telegram_bot_chatid
  - name: telegram_status
    platform: telegram
    chat_id: !secret telegram_status_chatid
  - name: telegram_logging
    platform: telegram
    chat_id: !secret telegram_logging_chatid
  - name: telegram_emergency
    platform: telegram
    chat_id: !secret telegram_emergency_chatid

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_bot_chatid
      - !secret telegram_status_chatid
      - !secret telegram_logging_chatid
      - !secret telegram_emergency_chatid

## WEATHER ##############################################################################
weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    mode: freedaily

## UTILITY METER ########################################################################
utility_meter:
  niu_watts_monthly:
    source: sensor.hs110_today_energy_kwh
    cycle: monthly
  niu_watts_yearly:
    source: sensor.hs110_today_energy_kwh
    cycle: yearly
  net_received_monthly:
    source: sensor.net_received
    cycle: monthly
  net_sent_monthly:
    source: sensor.net_sent
    cycle: monthly

## PING #################################################################################
binary_sensor:
  - platform: ping
    host: 192.168.0.37
    count: 1
    scan_interval: 30
    name: TV Schlafzimmer
  - platform: command_line
    name: "TV Schlafzimmer - Netflix"
    command: '/usr/bin/nmap -p9080 192.168.0.37 | /bin/grep open > /dev/null && (echo ON) || (echo OFF)'
    device_class: power

proximity:
  home_julienne: 
    ignored_zones:
      - AnneFred
      - ElenaKlinik
      - MarcNicole
      - Neovia
      - Papito
    devices:
      - device_tracker.google_maps_109408471456601103538
    tolerance: 50
  home_andre: 
    ignored_zones:
      - AnneFred
      - ElenaKlinik
      - MarcNicole
      - Neovia
      - Papito
    devices:
      - device_tracker.google_maps_108265044794977597376
      - device_tracker.life360_andre
    tolerance: 50

lovelace_gen:

pi_hole:
  - host: 192.168.0.2:80
    api_key: !secret pi_hole_api_key

input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number
scene: !include scenes.yaml
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensor
